### ISSUE TITLE
ssl success and no link 

### ISSUE THREAD

**Issue by ghost** [ToshY/mp4upload-dl#1]
Warning: file_get_contents(): SSL: Success in /storage/emulated/0/htdocs/mp4upload.php on line 7

https://.mp4upload.com:/d//video.mp4

line 7: preg_match('/(?P<server>w{3}\d{1,2}).*(?P<string>[a-zA-Z0-9]{56}).(?P<port>\d{3})/', file_get_contents("https://www.mp4upload.com/embed-".$embedId.".html"), $result);

**Comment by ToshY** [comment]
I've just took a quick look, and while I've edited it just now, I think it's no longer possible to get the direct link to the files anymore, because it's throwing a 403 for several public files. Besides, it's been 2 years since I added this snippet, so I'm not surprised they updated their "security" in the meantime.
